/*
 * Corn3 - Copyright (C) 2014 Xo Wang
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * Except as contained in this notice, the name(s) of the above copyright
 * holders shall not be used in advertising or otherwise to promote the sale,
 * use or other dealings in this Software without prior written authorization.
 */

/**
 * @file Declares InverterInterface, an interface that sets the state of the
 *       three phase inverter.
 */

#ifndef MOTOR_INVERTER_INTERFACE_H_
#define MOTOR_INVERTER_INTERFACE_H_

#include "motor/common.h"

/**
 * @brief Loads and synchronizes the pulse widths output by a three phase
 *        inverter.
 *
 * @note The inverter is defined as a set of three "phases" or "channels" for
 *       driving the three leads of of a motor.
 *
 * @note Each channel has two states:
 *         1) Disabled. This means that the channel driven to neither high nor
 *            low voltage power rails. It is also known as "high-impedance."
 *            This is commonly used in "six-step" commutation for sensing the
 *            back EMF generated by the motor in one phase.
 *         2) Enabled. This means that the channel is driven either high or low
 *            in a cyclic fashion. The duration of each cycle is the period, and
 *            the time during which the channel is driven high, or is "active,"
 *            is the "pulse width," or just "width." Conversely, for the rest of
 *            the time per cycle, the channel is driven low, or is "inactive."
 *
 * @note At a high enough frequency, this "pulse-width modulation" (PWM) scheme
 *       approximates a voltage source that generates a fraction of the voltage
 *       at the power rails, at each inverter channel.
 */
class InverterInterface {
 public:
  enum Channel {
    kChannelA,
    kChannelB,
    kChannelC,
    kNumChannels
  };

  virtual ~InverterInterface() {
  }

  /**
   * @brief Gets the pulse width modulation (PWM) generator period.
   *
   * @note This is one more than the highest value that the PWM counter will
   *       count to.
   *
   * @note The PWM clock and PWM counter refer to different concepts and they
   *       do not necessarily have the same frequency.
   *
   * @return Period of PWM, as counts of PWM clocks.
   */
  virtual Width16 GetPeriod() = 0;

  /**
   * @brief Loads the state (output or high impedance) and active time (pulse
   *        width) into an inverter channel.
   *
   * @note This does not necessarily immediately change the status a channel.
   *       Instead the new widths and states may be loaded at a later time, e.g.
   *       to simultaneous configure all channels, and not necessarily together.
   *       So, even a disabled channel should have some valid width, as it may
   *       continue to generate a pulse of that width until its state takes
   *       effect.
   *
   * @param channel Channel to write to.
   * @param width Duration of each PWM period that channel is driven high.
   * @param enable True if channel is driven (i.e. not high impedance).
   */
  virtual void WriteChannel(Channel channel,
                            Width16 width,
                            bool enable = true) = 0;

  /**
   * @brief Forces mode changes to channels to take effect immediately.
   */
  virtual void SyncModes() = 0;
};

#endif  /* MOTOR_INVERTER_INTERFACE_H_ */
